name: auto_release
on: 
  pull_request:
    types: [closed]

jobs:
  tag_for_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
        versionSpec: '5.2.x'
    
    - uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - name: Use GitVersion
      id: gitversion 
      uses: gittools/actions/gitversion/execute@v0.9.2

    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.ENDJIN_BOT_APP_ID }}
        private_key: ${{ secrets.ENDJIN_BOT_PRIVATE_KEY }}

    - uses: hole19/git-tag-action@master
      env:
        TAG: ${{ steps.gitversion.outputs.semver }}
        GITHUB_TOKEN: '${{ steps.generate_token.outputs.token }}'