name: build
on:
  push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run Pester tests
    steps:
    - uses: actions/checkout@v2
    - run: pwsh -f ./run-tests.ps1
  publish:
    runs-on: ubuntu-latest
    name: Publish to PowerShell Gallery
    needs: run_tests
    if: github.ref == 'refs/heads/master'
    steps:
    - run: |
        Publish-Module -Name .\module\Endjin.PRAutoflow.psd1 -NuGetApiKey ${{ secrets.ENDJIN_NUGET_APIKEY }} -Verbose
      shell: pwsh
      name: Publish module
    
