name: build
on:
  push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run Pester tests
    steps:
    - uses: actions/checkout@v2
    - run: pwsh -f ./module/run-tests.ps1
    - run: pwsh -f ./actions/run-tests.ps1
