name: build
on:
- push
- workflow_dispatch

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Run Pester tests
    steps:
    - uses: actions/checkout@v2
    - run: pwsh -f ./run-tests.ps1

  run_gitversion:
    runs-on: ubuntu-latest
    name: Run GitVersion
    outputs:
      semver: ${{ steps.gitversion.outputs.semver }}
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
        versionSpec: '5.2.x'
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Use GitVersion
      id: gitversion 
      uses: gittools/actions/gitversion/execute@v0.9.2

  publish:
    runs-on: ubuntu-latest
    name: Publish to PowerShell Gallery
    needs:
    - run_tests
    - run_gitversion
    if: github.ref == 'refs/heads/master' && steps.gitversion.outputs.preReleaseTag == ''
    steps:
    - uses: actions/checkout@v2
    - run: |
        Update-ModuleManifest -Path .\module\Endjin.PRAutoflow.psd1 -ModuleVersion ${{ needs.run_gitversion.outputs.semver }} -FunctionsToExport @("*")
        Publish-Module -Name .\module\Endjin.PRAutoflow.psd1 -NuGetApiKey ${{ secrets.ENDJIN_PSGALLERY_APIKEY }} -Verbose
      shell: pwsh
      name: Publish module
    
